### ISSUE TITLE
Doesn't hook into wp_upload_dir()

### ISSUE THREAD

**Issue by tdtm** [gwa/WpMultisiteDirectoryResolver#25]
This issue has been discovered with the plugin RAMP when trying to test remote connectivity in the plugin's settings.

Running: 
- bedrock-multisite skeleton @531964f675
- WordPress 4.3.1
- PHP v 5.5.26
- WpMultisiteDirectoryResolver @9d92e19797

When calling wp_upload_dir(), returned URLs for `url`, `baseurl` are of the form `//example.dev//app/uploads`. Notice the double slashes and lack of protocol.

None of the filters are added to process it.

I'm working on a fix - that's my first contribution ever, though, so feel free to criticize/look twice/etc - and will follow up shortly.

**Comment by tdtm** [comment]
Did a branch and fix to my fork. Will test before making a pull request.

https://github.com/tdtm/WpMultisiteDirectoryResolver/commit/ab466307d9593392201a1611cc3d8893474cf0ea

**Comment by prisis** [comment]
hi :) @tdtm, i will check it tomorrow and test it too.

**Comment by tdtm** [comment]
Found a bug in the way I did it. Updating shortly.

**Comment by tdtm** [comment]
Done. Should be good now!

**Comment by tdtm** [comment]
The tests give me an issue with the added trailing slash. It was necessary for me to add that slash on my WP install... Not sure if it's an issue in my configuration, in that case?

The other failure is the number of added filters; my mistake, I did not edit the tests to match the additions.

**Comment by prisis** [comment]
I will take a look at it.

**Comment by prisis** [comment]
Added test for your changes, now it should work for you

**Comment by tdtm** [comment]
Haven't had time to look into it, but tried to update to the most recent version and I get 
`Fatal error: Call to a member function addFilter() on a non-object in /home/mysitename/develop/releases/20150929181238/vendor/gwa/multisite-directory-resolver/src/Gwa/AbstractResolver.php on line 135`

**Comment by prisis** [comment]
Did you run composer update?, im using it on a new project and it works...

Because i can't reproduce it

**Comment by tdtm** [comment]
I cleared my old composer.lock and ran update.
It did fetch the dependencies but it appears that the interaction with wpBridge fails.

**Comment by prisis** [comment]
Can you donwload the latest bedrock-multisite skeleton and test it?

**Comment by tdtm** [comment]
Ah yes that might be related to that. You can close this issue, if there is anything after this update, I'll open a new issue!
