### ISSUE TITLE
Trait not found

### ISSUE THREAD

**Issue by abelley** [gwa/WpMultisiteDirectoryResolver#35]
I got this error in my wordpress project after a composer update :

> Fatal error: Trait 'Gwa\Wordpress\MockeryWpBridge\Traits\WpBridgeTrait' not found in /vendor/gwa/multisite-directory-resolver/src/Gwa/MultisiteResolverManager.php on line 26

I think it's related to the latest update of WpBridge v1.3

I've changed the line 16 in _MultisiteResolverManager.php_ AND _AbstractResolver.php_ for 
`use Gwa\Wordpress\WpBridge\Traits\WpBridgeTrait;` and it's now working

**Comment by prisis** [comment]
Hey :), 
i fixed this bug, i did a mistake in the releases... now it works.
